### PR TITLE
Use GitHub Actions to protect against build errors

### PR DESCRIPTION
**Pull request by hartwork**
Can be seen in action at https://github.com/hartwork/spacenavd/actions

What do you think?

### CODE REVIEW

**Comment by jtsiomb** [comment]
I'm not sure I want to add a `.github` directory in my project root. I think I'll pass on this one.

**Comment by hartwork** [comment]
Travis and AppVeyor also use a file in your repository for configuration (at least commonly).
So you don't want an CI at all or a different CI? Why?

**Comment by jtsiomb** [comment]
I don't use tools for automated testing. Never have.

**Comment by hartwork** [comment]
This thing could help is making sure that neither `--enable-x11` nor `--disable-x11` ever fails to built undetected again. So there was a time before testing in your life but why not starting to do that now, especially if it comes "for free"?

**Comment by jtsiomb** [comment]
The benefit of catching these corner-cases is too marginal to start including irrelevant junk files in my source. If it could work without having to pollute my code with extra files, I would not be opposed to it.

**Comment by hartwork** [comment]
> The benefit of catching these corner-cases is too marginal to start including irrelevant junk files in my source. If it could work without having to pollute my code with extra files, I would not be opposed to it.

We'd catch all sorts of compile errors before the hit packages and end-users but I don't think we'll get somewhere on this matter with an attitude of "marginal corner-cases" and "irrelevant junk files". You made a decision, I'll accept it, we move on.

**Pull request closed without merging**
