### PR TITLE
Dominant axis

### PR DESCRIPTION
**Pull request by albfan**
Not even near to work, this PR filter dominant axis to apply only its movement

TODOS:
- Translation seems to be starting event for all interactions, so a threshold is needed to allow rotation to take dominance
- All printf is for debug (remove)
- Find exact threshold for a movement to be stopped and ready to take a different one.
- Axis from spacenav looks rotated from user view (see screencast):

Official driver implementation:
official-driver-dominant-axis

Erratic from this PR:
spacenav-driver-dominant-axis

fixes #63

### CODE REVIEW

**Comment by albfan** [comment]
I reworked the implementation using:

- Threshold to decide dominant axis when still there's no one defined: Set to 3
- Time since last dominant movement to allow new dominant axis: Set to 0.2s

 Probably this settings needs to be customizable

dominant-axis

**Comment by albfan** [comment]
Reworked on top of latest changes.

https://github.com/FreeSpacenav/spnavcfg/pull/33 is open to setup. If treshold for movement or time range for inactivity needs config we can address there

I will try to collect feedback on windows implementation to compare behaviour, but implementation feels correct now

Let me know if any coding style or detail is missing

**Comment by jtsiomb** [comment]
I haven't tried it yet, but the code changes look nice and succint. At first glance there are minor style differences from how I'd write it, but nothing that would hold back a merge. If you want to collect feedback first, let me know when you think it's final and ready for merging.

**Comment by albfan** [comment]
Sure, and I will take a look at whole code styling. Give me two days

**Comment by albfan** [comment]
I test the dominant on windows and this implementation is even smoother.

They call it navigation "dominant" which probably makes sense as this is not only about axis.

I can change that and review the code ant this should be ready

**Comment by jtsiomb** [comment]
I made some minor changes, and I'll go ahead and merge this for now. But I have a question: is it supposed to stop rotations while translating and vise-versa, or should the rotation and translation axis locks be independent? I've never used dominant axis mode before, but this just feels annoying.

**Comment by albfan** [comment]
It just choose one movement between 6 options (3 translations, 3 rotations)

**Comment by jtsiomb** [comment]
I pulled out my SGI O2 where I have 3Dconnexion drivers, and tested the dominant axis mode. It does not work like this. There's no need for timers, it just reports only the motion with the largest magnitude at any given time. If we're in the middle of a slow translation on the X axis, and without removing the side-pressure we also tilt the cap harder, it will switch to a rotation immediately.

**Comment by albfan** [comment]
I can change that implementation then, but, as said this looks smooth than windows, as it continues using same axis or rotation if change is small

**Comment by jtsiomb** [comment]
The timeouts feel awkward. The original behavior on the SGI felt much better. At the very least we need to try both and compare, but you don't *have* to do it, I'm just recording issues for future reference. I could try it myself at some point.

**Pull request merged**
